// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Aspose" file="SaaSposeResponseTests.cs">
//   Copyright (c) 2018 Aspose.CAD for Cloud
// </copyright>
// <summary>
//   Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
// 
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
// 
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

using NUnit.Framework;

using System;
using System.IO;
using System.Collections.Generic;
using System.Net;
using Aspose.CAD.Cloud.Sdk;
using Aspose.CAD.Cloud.Sdk.Model;
using Aspose.CAD.Cloud.Sdk;
using System.Reflection;
using Newtonsoft.Json;
using Aspose.Storage.Cloud.Sdk.Api;
using Aspose.Storage.Cloud.Sdk.Model;

namespace Aspose.CAD.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SaaSposeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SaaSposeResponseTests
    {
        // TODO uncomment below to declare an instance variable for SaaSposeResponse
        //private SaaSposeResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SaaSposeResponse
            //instance = new SaaSposeResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SaaSposeResponse
        /// </summary>
        [Test]
        public void SaaSposeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SaaSposeResponse
            //Assert.IsInstanceOfType<SaaSposeResponse> (instance, "variable 'instance' is a SaaSposeResponse");
        }

        /// <summary>
        /// Test deserialize a ImagePropertiesResponse from type SaaSposeResponse
        /// </summary>
        [Test]
        public void ImagePropertiesResponseDeserializeFromSaaSposeResponseTest()
        {
            // TODO uncomment below to test deserialize a ImagePropertiesResponse from type SaaSposeResponse
            //Assert.IsInstanceOf<SaaSposeResponse>(JsonConvert.DeserializeObject<SaaSposeResponse>(new ImagePropertiesResponse().ToJson()));
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }
}
